#!/bin/sh


if [ "$SKIP_HOOKS" == "true" ] || git config --get hooks.skipchecks | grep -q 'true'; then
    echo "Bypassing checks."
    exit 0
fi



if ! gem list rubocop -i > /dev/null; then
    echo "rubocop not found! Installing..."
    gem install rubocop
fi

# Check if reek is installed
if ! gem list reek -i > /dev/null; then
    echo "reek not found! Installing..."
    gem install reek
fi

# Check if flog is installed
if ! gem list flog -i > /dev/null; then
    echo "flog not found! Installing..."
    gem install flog
fi

echo "Running pre-push check..."

# Get the list of changed files
files=$(git diff master --name-only --diff-filter=d)

echo "linting... $files"
for file in $files; do
    if [[ "$file" =~ \.rb$ ]]; then
        echo "Running linter for $file" 
        rubocop_result=$(rubocop "$file")
        rubocop_exit_code=$?
        rubocop --auto-correct "$file"
        if [ $rubocop_exit_code -ne 0 ]; then
            echo "RuboCop failed for $file:"
            echo "$rubocop_result"
            exit 1
        fi
        
        reek_result=$(reek "$file")
        reek_exit_code=$?
        if [ $reek_exit_code -ne 0 ]; then
            echo "Reek smells detected for $file:"
            echo "$reek_result"
            exit 1
        fi
        
        flog_result=$(flog "$file")
        # Adjust this based on a threshold you consider "complex"
        if [[ $(echo "$flog_result" | head -1 | awk '{print $2}') > 20 ]]; then
            echo "Flog complexity too high for $file:"
            echo "$flog_result"
            exit 1
        fi
    fi
done

echo "saving diff to files..."
DIFF_CONTENT=$(git diff master)

PROMPT="Can you evaluate this code difference for readability, code smells, refactor hints, opportunities to apply specific design patterns and  SOLID principles?\n\n"

# Split the DIFF_CONTENT into chunks of 6000 characters and save to files
count=1
mkdir -p pre_push_diffs

while [ -n "$DIFF_CONTENT" ]; do
    # Grab the first 6000 characters
    CHUNK="${DIFF_CONTENT:0:6000}"

    # Remove the first 6000 characters from DIFF_CONTENT
    DIFF_CONTENT="${DIFF_CONTENT:6000}"

    # Write the chunk to a file with the prompt within the pre_push_diffs folder
    echo -e "$PROMPT$CHUNK" > "pre_push_diffs/pre_push_diff_${count}.txt"

    count=$((count + 1))
done

echo "Diffs have been saved to multiple files (pre_push_diffs/pre_push_diff_X.txt) with the prompt. Please review each file before pushing."

exit 0
