#!/bin/sh

if [ "$SKIP_HOOKS" == "true" ] || git config --get hooks.skipchecks | grep -q 'true'; then
    echo "Bypassing checks."
    exit 0
fi

# Check if ruff is installed
if ! pip list | grep -q ruff; then
    echo "ruff not found! Installing..."
    pip install ruff
fi

# Check if radon is installed
if ! pip list | grep -q radon; then
    echo "radon not found! Installing..."
    pip install radon
fi

echo "Running pre-push check..."

# Get the list of changed files
files=$(git diff master --name-only --diff-filter=d)

echo "Linting with ruff... $files"
for file in $files; do
    if [[ "$file" =~ \.py$ ]]; then
        echo "Running linter for $file" 
        ruff_result=$(ruff check "$file")
        ruff_exit_code=$?
        if [ $ruff_exit_code -ne 0 ]; then
            echo "Ruff linting failed for $file:"
            echo "$ruff_result"
            exit 1
        fi
        
        # Check cyclomatic complexity with radon
        radon_result=$(radon cc "$file" -nc)
        radon_exit_code=$?
        if [ $radon_exit_code -ne 0 ]; then
            echo "Radon complexity check failed for $file:"
            echo "$radon_result"
            exit 1
        fi
    fi
done

echo "saving diff to files..."
DIFF_CONTENT=$(git diff master)

PROMPT="Can you evaluate this code difference for readability, code smells, refactor hints, opportunities to apply specific design patterns and SOLID principles?\n\n"

# Split the DIFF_CONTENT into chunks of 6000 characters and save to files
count=1
mkdir -p pre_push_diffs

while [ -n "$DIFF_CONTENT" ]; do
    # Grab the first 6000 characters
    CHUNK="${DIFF_CONTENT:0:6000}"

    # Remove the first 6000 characters from DIFF_CONTENT
    DIFF_CONTENT="${DIFF_CONTENT:6000}"

    # Write the chunk to a file with the prompt within the pre_push_diffs folder
    echo -e "$PROMPT$CHUNK" > "pre_push_diffs/pre_push_diff_${count}.txt"

    count=$((count + 1))
done

echo "Diffs have been saved to multiple files (pre_push_diffs/pre_push_diff_X.txt) with the prompt. Please review each file before pushing."

exit 0
